// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var _providers;
    _providers = [];
    return {
      set: function(name, provider, isDefault) {
        isDefault = (typeof true !== "undefined" && true !== null ? true : isDefault === void 0) && _providers.length === 0;
        _providers[name] = provider;
        if (isDefault) {
          return _providers["__DEF__"] = provider;
        }
      },
      get: function(name) {
        if (!name) {
          name = "__DEF__";
        }
        return _providers[name];
      }
    };
  });

}).call(this);
