// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(["Ural/Modules/pubSub"], function(pubSub) {
    var ViewModel;
    return ViewModel = (function() {

      function ViewModel(resource, parentItem) {
        this.resource = resource;
        this.parentItem = parentItem;
        this.useGetNewRemote = true;
      }

      ViewModel.prototype.completeUpdate = function(data) {
        if (this.src) {
          return this.src.item.map(data);
        } else {
          return this.map(data);
        }
      };

      ViewModel.prototype.completeCreate = function(data) {
        this.setSrc(null, null);
        return this.map(data);
      };

      ViewModel.prototype.map = function(data) {
        var d, dataIndexVM, prop;
        if ($.isArray()) {
          data = data[0];
        }
        dataIndexVM = {};
        for (prop in this) {
          if (!__hasProp.call(this, prop)) continue;
          if (this[prop] && data[prop] && this[prop].list) {
            dataIndexVM[prop] = data[prop];
            delete data[prop];
          }
        }
        for (prop in data) {
          if (!__hasProp.call(data, prop)) continue;
          d = this.tryDate(data[prop]);
          if (d) {
            data[prop] = d;
          }
        }
        ko.mapping.fromJS(data, {}, this);
        for (prop in dataIndexVM) {
          if (!__hasProp.call(dataIndexVM, prop)) continue;
          this[prop].map(dataIndexVM[prop]);
        }
        return this.errors = ko.validation.group(this);
      };

      ViewModel.prototype.tryDate = function(str) {
        var match;
        if (str && typeof str === "string") {
          match = /\/Date\((\d+)\)\//.exec(str);
          if (match) {
            return moment(str).toDate();
          }
        }
      };

      ViewModel.prototype.clone = function(status) {
        var vm;
        vm = this.onCreate();
        vm.map(this.toData());
        vm.setSrc(this, status);
        return vm;
      };

      ViewModel.prototype.onCreate = function() {
        return new ViewModel(this.resource, this.parentItem);
      };

      ViewModel.prototype.setSrc = function(item, status) {
        return this.src = {
          item: item,
          status: status
        };
      };

      ViewModel.prototype.cancel = function(item, event) {
        event.preventDefault();
        return pubSub.pub("crud", "cancel", {
          resource: this.resource,
          status: this.src.status
        });
      };

      ViewModel.prototype.confirmEvent = function(event, eventName) {
        var attr;
        attr = $(event.target).attr("data-bind-event");
        return !attr || attr === eventName;
      };

      ViewModel.prototype.startUpdate = function(item, event) {
        if (this.confirmEvent(event, "startUpdate")) {
          event.preventDefault();
          return pubSub.pub("crud", "start_update", this.clone("update"));
        }
      };

      ViewModel.prototype.startRemove = function(item, event) {
        if (this.confirmEvent(event, "startRemove")) {
          event.preventDefault();
          return pubSub.pub("crud", "start_delete", this.clone("delete"));
        }
      };

      ViewModel.prototype.create = function(item, event) {
        if (this.confirmEvent(event, "create")) {
          event.preventDefault();
          return pubSub.pub("crud", "create", this);
        }
      };

      ViewModel.prototype.update = function(item, event) {
        if (this.confirmEvent(event, "update")) {
          event.preventDefault();
          return pubSub.pub("crud", "update", this);
        }
      };

      ViewModel.prototype.remove = function(item, event) {
        if (this.confirmEvent(event, "remove")) {
          event.preventDefault();
          return pubSub.pub("crud", "delete", this);
        }
      };

      ViewModel.prototype.details = function(item, event) {
        if (this.confirmEvent(event, "details")) {
          event.preventDefault();
          return pubSub.pub("crud", "details", this.clone("details"));
        }
      };

      ViewModel.prototype.setErrors = function(errs) {
        var err, flag, rule, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = errs.length; _i < _len; _i++) {
          err = errs[_i];
          flag = false;
          rule = this[err.field].rules().filter(function(f) {
            return f.params === "custom";
          })[0];
          if (rule) {
            this[err.field].rules.remove(rule);
          }
          _results.push(this[err.field].extend({
            validation: {
              params: "custom",
              validator: function(val, otherVal) {
                var _flag;
                _flag = flag;
                flag = true;
                return _flag;
              },
              message: err.message
            }
          }));
        }
        return _results;
      };

      ViewModel.prototype.toData = function() {
        return ko.mapping.toJS(this);
      };

      return ViewModel;

    })();
  });

}).call(this);
