// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var postbox;
    postbox = new ko.subscribable();
    return {
      pub: function(target, topic, data) {},
      sub: function(target, topic, callback) {
        return postbox.subscribe(topic, callback);
      }
    };
  });

}).call(this);
