// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    return {
      wrong_data: "Wrong data",
      success: "Success",
      created_success: "Created successfully",
      updated_success: "Updated successfully",
      deleted_success: "Deleted successfully"
    };
  });

}).call(this);
